version: '3.8'

services:
  # MySQL Database
  db:
    image: mysql:8.0
    container_name: demo-app-db
    restart: unless-stopped
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: noteapp
      MYSQL_ROOT_HOST: "%"
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - demo-app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

  # Node.js Application
  app:
    build: .
    container_name: demo-app
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=password
      - DB_NAME=noteapp
      - PORT=3000
    depends_on:
      db:
        condition: service_healthy
    networks:
      - demo-app-network
    command: npm start



volumes:
  mysql_data:

networks:
  demo-app-network:
    driver: bridge 
